from __future__ import annotations

import re
import subprocess
import sys
import tempfile
from pathlib import Path

from fc_editor.codecs.custom_music import CustomMusicCodec


ROOT = (
    Path(sys._MEIPASS)
    if getattr(sys, "frozen", False) and hasattr(sys, "_MEIPASS")
    else Path(__file__).resolve().parents[2]
)
ASM6 = (
    ROOT
    / "analysis"
    / "FamiStudio-4.5.3-source"
    / "FamiStudio-4.5.3"
    / "Tools"
    / "asm6_fixed.exe"
)
MAX_SOURCE_SIZE = 4 * 1024 * 1024
FORBIDDEN_DIRECTIVE = re.compile(
    r"^\s*\.(?:include|incbin|base|org)\b", re.IGNORECASE | re.MULTILINE
)


def load_music_bank(path: str | Path) -> bytes:
    source = Path(path)
    payload = source.read_bytes()
    CustomMusicCodec.validate_bank(payload)
    return payload


def assemble_famistudio_music_source(path: str | Path) -> bytes:
    """Assemble one self-contained FamiStudio ASM6 data export into an 8 KiB bank."""

    source = Path(path)
    if not ASM6.is_file():
        raise FileNotFoundError(f"未找到随项目附带的 ASM6：{ASM6}")
    if source.stat().st_size > MAX_SOURCE_SIZE:
        raise ValueError("ASM 源文件超过 4 MiB 安全上限。")
    try:
        text = source.read_text(encoding="utf-8-sig")
    except UnicodeDecodeError as error:
        raise ValueError("ASM 源文件必须使用 UTF-8 或 UTF-8 BOM 编码。") from error
    if not re.search(r"(?im)^\s*music_data_[A-Za-z0-9_]+\s*:", text):
        raise ValueError("没有找到 FamiStudio 的 music_data_* 数据标签。")
    directive = FORBIDDEN_DIRECTIVE.search(text)
    if directive is not None:
        raise ValueError(
            f"为保证可复现和路径安全，不允许导入源包含 {directive.group(0).strip()} 指令。"
        )

    wrapper = (
        "; Generated by New DC Modifier.\n"
        "    .fillvalue $00\n"
        "    .base $8000\n"
        f"{text.rstrip()}\n"
        "music_data_import_end:\n"
        "    .org $a000\n"
    )
    with tempfile.TemporaryDirectory(prefix="new_dc_music_") as temporary:
        directory = Path(temporary)
        asm_path = directory / "music.asm"
        output_path = directory / "music.bin"
        listing_path = directory / "music.lst"
        asm_path.write_text(wrapper, encoding="utf-8", newline="\n")
        try:
            result = subprocess.run(
                [str(ASM6), asm_path.name, output_path.name, listing_path.name],
                cwd=directory,
                check=False,
                capture_output=True,
                text=True,
                timeout=30,
            )
        except subprocess.TimeoutExpired as error:
            raise RuntimeError("ASM6 组装超过 30 秒，已取消。") from error
        if result.returncode:
            details = (result.stdout + result.stderr).strip()
            raise RuntimeError(f"ASM6 组装失败：{details or '未返回错误详情'}")
        if not output_path.is_file():
            raise RuntimeError("ASM6 没有生成音乐银行文件。")
        payload = output_path.read_bytes()

    CustomMusicCodec.validate_bank(payload)
    return payload
